// <auto-generated />
using System;
using GalleryMVC.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GalleryMVC.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231018165329_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-rc.1.23419.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GalleryMVC.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20077903-161a-44db-89de-c6684ae7e54d"),
                            Developer = "CD PROJEKT RED",
                            Price = 59.99m,
                            Publisher = "CD PROJEKT RED",
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = new Guid("f4a9f91c-23aa-4924-868a-0d203502ffdc"),
                            Developer = "Bethesda Game Studios",
                            Price = 69.99m,
                            Publisher = "Bethesda Softworks",
                            Title = "Starfield"
                        },
                        new
                        {
                            Id = new Guid("670f2e23-94e4-4f51-9dd1-57fae8c91f80"),
                            Developer = "Valve",
                            Price = 0m,
                            Publisher = "Valve",
                            Title = "Dota 2"
                        },
                        new
                        {
                            Id = new Guid("3955d5a2-d278-4514-a128-3753696128df"),
                            Developer = "Larian Studios",
                            Price = 59.99m,
                            Publisher = "Larian Studios",
                            Title = "Baldur's Gate 3"
                        },
                        new
                        {
                            Id = new Guid("2b6ccb7e-33f4-44c6-ba81-f5b557f0eab9"),
                            Developer = "Klei Entertainment",
                            Price = 9.99m,
                            Publisher = "Klei Entertainment",
                            Title = "Don't Starve"
                        },
                        new
                        {
                            Id = new Guid("d928e878-2672-4234-bd83-82d03108e952"),
                            Developer = "Wube Software LTD.",
                            Price = 35.00m,
                            Publisher = "Wube Software LTD.",
                            Title = "Factorio"
                        },
                        new
                        {
                            Id = new Guid("7cb71ee8-c2d6-4e84-8f51-37fec48fa104"),
                            Developer = "Klei Entertainment",
                            Price = 24.99m,
                            Publisher = "Klei Entertainment",
                            Title = "Oxygen Not Included"
                        },
                        new
                        {
                            Id = new Guid("aa1ffc19-9bc2-45e8-ad4b-1921d1988c45"),
                            Developer = "CD PROJEKT RED",
                            Price = 39.99m,
                            Publisher = "CD PROJEKT RED",
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = new Guid("c4a57d79-1564-4c8c-a809-3f4cd5a58623"),
                            Developer = "Bethesda Game Studios",
                            Price = 19.99m,
                            Publisher = "Bethesda Softworks",
                            Title = "The Elder Scrolls V: Skyrim"
                        },
                        new
                        {
                            Id = new Guid("09bf6c7d-39aa-4a61-98ac-56bea91e6faa"),
                            Developer = "Valve",
                            Price = 0m,
                            Publisher = "Valve",
                            Title = "Counter-Strike 2"
                        },
                        new
                        {
                            Id = new Guid("620441b4-9dd7-4b43-b045-d812f9cea10a"),
                            Developer = "Larian Studios",
                            Price = 44.99m,
                            Publisher = "Larian Studios",
                            Title = "Divinity: Original Sin 2"
                        },
                        new
                        {
                            Id = new Guid("a6dec3cb-b081-4684-8408-85d479aa0448"),
                            Developer = "ConcernedApe",
                            Price = 14.99m,
                            Publisher = "ConcernedApe",
                            Title = "Stardew Valley"
                        },
                        new
                        {
                            Id = new Guid("a20e924d-28b0-4259-8d81-ca15af01ecd9"),
                            Developer = "FromSoftware",
                            Price = 59.99m,
                            Publisher = "Activision",
                            Title = "Sekiro: Shadows Die Twice"
                        });
                });

            modelBuilder.Entity("GalleryMVC.Models.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ec62502-42a6-4908-8035-b2587ede74f8"),
                            Name = "RPG"
                        },
                        new
                        {
                            Id = new Guid("f51ad048-169a-476d-8f01-df37dfac66dd"),
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("eb36bf4f-5116-484b-befb-df343e136b2e"),
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = new Guid("06398b44-7d13-4b77-8904-d44a1268301f"),
                            Name = "Free to Play"
                        },
                        new
                        {
                            Id = new Guid("f1f300c5-1945-4656-ab9c-00daf2dcedab"),
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("0389e44f-1f5a-4d6e-9423-3951322f5fd1"),
                            Name = "Indie"
                        },
                        new
                        {
                            Id = new Guid("2a22b6c9-52bf-4cd3-9b7a-23c71910a122"),
                            Name = "Simulation"
                        },
                        new
                        {
                            Id = new Guid("8117cb3b-ee33-4c6c-bf78-7cf9ea58d502"),
                            Name = "Shooter"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
