// <auto-generated />
using System;
using GalleryMVC.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GalleryMVC.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231018194426_addCreateDateAndLastEidtedDateAttributes")]
    partial class addCreateDateAndLastEidtedDateAttributes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-rc.1.23419.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GalleryMVC.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastEditedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7edb1882-dd74-4bdb-a141-d7eef4eedd6e"),
                            CreatedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5557),
                            Developer = "CD PROJEKT RED",
                            LastEditedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5559),
                            Price = 59.99m,
                            Publisher = "CD PROJEKT RED",
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = new Guid("8a68792a-8c57-4680-b89f-4fd146570e45"),
                            CreatedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5563),
                            Developer = "Bethesda Game Studios",
                            LastEditedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5563),
                            Price = 69.99m,
                            Publisher = "Bethesda Softworks",
                            Title = "Starfield"
                        },
                        new
                        {
                            Id = new Guid("c6ed4b98-0556-435f-8940-f7d486286cbd"),
                            CreatedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5566),
                            Developer = "Valve",
                            LastEditedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5567),
                            Price = 0m,
                            Publisher = "Valve",
                            Title = "Dota 2"
                        },
                        new
                        {
                            Id = new Guid("76732f24-ed23-46c5-993b-573ed3544175"),
                            CreatedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5569),
                            Developer = "Larian Studios",
                            LastEditedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5569),
                            Price = 59.99m,
                            Publisher = "Larian Studios",
                            Title = "Baldur's Gate 3"
                        },
                        new
                        {
                            Id = new Guid("422eb0eb-0ffb-4d2c-aae0-fc16469ee91a"),
                            CreatedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5572),
                            Developer = "Klei Entertainment",
                            LastEditedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5573),
                            Price = 9.99m,
                            Publisher = "Klei Entertainment",
                            Title = "Don't Starve"
                        },
                        new
                        {
                            Id = new Guid("4d5450ca-6149-4957-987c-9ce996dab04a"),
                            CreatedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5575),
                            Developer = "Wube Software LTD.",
                            LastEditedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5576),
                            Price = 35.00m,
                            Publisher = "Wube Software LTD.",
                            Title = "Factorio"
                        },
                        new
                        {
                            Id = new Guid("fe4e43e1-0c16-4e88-a962-d0c9d4cf4b1e"),
                            CreatedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5578),
                            Developer = "Klei Entertainment",
                            LastEditedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5578),
                            Price = 24.99m,
                            Publisher = "Klei Entertainment",
                            Title = "Oxygen Not Included"
                        },
                        new
                        {
                            Id = new Guid("46489170-424c-4b84-bf04-b95fbab4e808"),
                            CreatedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5581),
                            Developer = "CD PROJEKT RED",
                            LastEditedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5581),
                            Price = 39.99m,
                            Publisher = "CD PROJEKT RED",
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = new Guid("45b13b93-d65c-46e9-b0d9-bd67f0a96cb1"),
                            CreatedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5586),
                            Developer = "Bethesda Game Studios",
                            LastEditedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5587),
                            Price = 19.99m,
                            Publisher = "Bethesda Softworks",
                            Title = "The Elder Scrolls V: Skyrim"
                        },
                        new
                        {
                            Id = new Guid("dd02828e-3806-468b-b3ce-7c42558a9ce7"),
                            CreatedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5589),
                            Developer = "Valve",
                            LastEditedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5589),
                            Price = 0m,
                            Publisher = "Valve",
                            Title = "Counter-Strike 2"
                        },
                        new
                        {
                            Id = new Guid("4a2087f2-4160-4c81-a483-f37a0922d443"),
                            CreatedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5591),
                            Developer = "Larian Studios",
                            LastEditedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5592),
                            Price = 44.99m,
                            Publisher = "Larian Studios",
                            Title = "Divinity: Original Sin 2"
                        },
                        new
                        {
                            Id = new Guid("227dd2b7-b1c1-465d-a9ed-2fdfcccc10ee"),
                            CreatedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5594),
                            Developer = "ConcernedApe",
                            LastEditedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5594),
                            Price = 14.99m,
                            Publisher = "ConcernedApe",
                            Title = "Stardew Valley"
                        },
                        new
                        {
                            Id = new Guid("6aa1c0a4-0934-4e51-a33b-e1a197bce73d"),
                            CreatedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5596),
                            Developer = "FromSoftware",
                            LastEditedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5597),
                            Price = 59.99m,
                            Publisher = "Activision",
                            Title = "Sekiro: Shadows Die Twice"
                        });
                });

            modelBuilder.Entity("GalleryMVC.Models.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastEditedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("96198011-bb28-4b09-8b40-249b8e8c5c67"),
                            CreatedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5765),
                            LastEditedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5765),
                            Name = "RPG"
                        },
                        new
                        {
                            Id = new Guid("4dca4171-1a21-47cd-bc37-b9730b46c6c0"),
                            CreatedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5768),
                            LastEditedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5768),
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("8a4b0785-7a97-4966-b33c-25ffcf2b96e5"),
                            CreatedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5770),
                            LastEditedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5771),
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = new Guid("233e98c9-d1e9-4d9a-b792-0989972e010c"),
                            CreatedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5776),
                            LastEditedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5777),
                            Name = "Free to Play"
                        },
                        new
                        {
                            Id = new Guid("c9d4ab26-bf24-4533-a3fd-0b9778f6ab11"),
                            CreatedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5778),
                            LastEditedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5779),
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("2b7e813e-b596-4814-9e17-cc3f6f8d3511"),
                            CreatedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5825),
                            LastEditedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5826),
                            Name = "Indie"
                        },
                        new
                        {
                            Id = new Guid("b3b45281-cce0-42d4-8ad3-d8ece0a2e55f"),
                            CreatedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5828),
                            LastEditedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5828),
                            Name = "Simulation"
                        },
                        new
                        {
                            Id = new Guid("1fe45c37-7610-41ba-bf04-b2fe44834b88"),
                            CreatedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5830),
                            LastEditedDate = new DateTime(2023, 10, 18, 19, 44, 25, 714, DateTimeKind.Utc).AddTicks(5830),
                            Name = "Shooter"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
